default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.db
  Database: dd16dmp9ph46c2
  username: xlnpwilzuuumfj
  host: ec2-107-23-76-12.compute-1.amazonaws.com
  password: 8acefc3afd75c960a29d28252d1e6bd0ff0ce4c6daa25442c21ace608b4612f7


