default: &default
  adapter: postgresql

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: d2s8fom04ghsnn
  username: mkqbapfyrcasks
  host: ec2-44-207-133-100.compute-1.amazonaws.com
  password: cf65c6031bf67af31f70c87bdd7c42e1030ed19c3121a054ba3cc7bc149eb1ca


